services:
  chatwave:
    image: ghcr.io/lifufkd/chatwave:latest
    build: .
    restart: unless-stopped
    volumes:
      - app_data:${MEDIA_FOLDER:-/app/data}
    env_file:
      - ".env"
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    networks:
      - backend

  web:
    image: ghcr.io/lifufkd/chatwave-web:latest
    restart: unless-stopped
    ports:
      - ${HTTP_WEB_PORT:-80}:80
      - ${HTTPS_WEB_PORT:-443}:443
    volumes:
      - ${SSL_CERTS_FOLDER}:/cert:ro
    env_file:
      - ".env"
    depends_on:
      - chatwave
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: unless-stopped
    ports:
      - ${API_PORT:-4433}:443
    volumes:
      - ${SSL_CERTS_FOLDER}:/cert:ro
    env_file:
      - ".env"
    depends_on:
      - chatwave
    networks:
      - backend

  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
       - POSTGRES_USER=${DB_USER:-admin}
       - POSTGRES_PASSWORD=${DB_PASSWORD:-admin}
       - POSTGRES_DB=${DB_DATABASE:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:
  app_data:

networks:
  backend: