services:
  chatwave:
    image: sbrse/chatwave:latest
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - app_data:/app/data
    env_file:
      - ".env"
    depends_on:
      - postgres
      - redis
    networks:
      - backend

  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:
  app_data:

networks:
  backend: