"""add avatar_name and avatar_type fields to Conversations table

Revision ID: 1700ae45e893
Revises: e7f9f9d0ac0f
Create Date: 2025-01-18 21:52:29.884005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1700ae45e893'
down_revision: Union[str, None] = 'e7f9f9d0ac0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('avatar_name', sa.String(), nullable=True), schema='chatwave')
    op.add_column('conversations', sa.Column('avatar_type', sa.String(), nullable=True), schema='chatwave')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'avatar_type', schema='chatwave')
    op.drop_column('conversations', 'avatar_name', schema='chatwave')
    # ### end Alembic commands ###
