"""remove avatar_url from Conversation table

Revision ID: 17785fb90385
Revises: 937a7ab8dd9e
Create Date: 2025-01-18 00:29:05.750768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17785fb90385'
down_revision: Union[str, None] = '937a7ab8dd9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'avatar_url', schema='chatwave')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True), schema='chatwave')
    # ### end Alembic commands ###
