"""fix data types, unique, indexes and nullable states in DB structure

Revision ID: 26c1b8940f53
Revises: 4a06c5d8b599
Create Date: 2025-01-27 20:22:39.252096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c1b8940f53'
down_revision: Union[str, None] = '4a06c5d8b599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chatwave_conversations_type', table_name='conversations', schema='chatwave')
    op.drop_index('ix_chatwave_conversations_updated_at', table_name='conversations', schema='chatwave')
    op.create_index(op.f('ix_chatwave_conversations_members_joined_at'), 'conversations_members', ['joined_at'], unique=False, schema='chatwave')
    op.create_index(op.f('ix_chatwave_conversations_members_role'), 'conversations_members', ['role'], unique=False, schema='chatwave')
    op.drop_index('ix_chatwave_messages_created_at', table_name='messages', schema='chatwave')
    op.drop_index('ix_chatwave_messages_updated_at', table_name='messages', schema='chatwave')
    op.create_index(op.f('ix_chatwave_messages_sender_id'), 'messages', ['sender_id'], unique=False, schema='chatwave')
    op.create_index(op.f('ix_chatwave_messages_status'), 'messages', ['status'], unique=False, schema='chatwave')
    op.drop_index('ix_users_username_passwordhash', table_name='users', schema='chatwave')
    op.drop_constraint('users_username_key', 'users', schema='chatwave', type_='unique')
    op.create_index(op.f('ix_chatwave_users_username'), 'users', ['username'], unique=True, schema='chatwave')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatwave_users_username'), table_name='users', schema='chatwave')
    op.create_unique_constraint('users_username_key', 'users', ['username'], schema='chatwave')
    op.create_index('ix_users_username_passwordhash', 'users', ['username', 'password_hash'], unique=False, schema='chatwave')
    op.drop_index(op.f('ix_chatwave_messages_status'), table_name='messages', schema='chatwave')
    op.drop_index(op.f('ix_chatwave_messages_sender_id'), table_name='messages', schema='chatwave')
    op.create_index('ix_chatwave_messages_updated_at', 'messages', ['updated_at'], unique=False, schema='chatwave')
    op.create_index('ix_chatwave_messages_created_at', 'messages', ['created_at'], unique=False, schema='chatwave')
    op.drop_index(op.f('ix_chatwave_conversations_members_role'), table_name='conversations_members', schema='chatwave')
    op.drop_index(op.f('ix_chatwave_conversations_members_joined_at'), table_name='conversations_members', schema='chatwave')
    op.create_index('ix_chatwave_conversations_updated_at', 'conversations', ['updated_at'], unique=False, schema='chatwave')
    op.create_index('ix_chatwave_conversations_type', 'conversations', ['type'], unique=False, schema='chatwave')
    # ### end Alembic commands ###
