"""Add auto add time event

Revision ID: 29c0b0235a54
Revises: 810e9a86bc77
Create Date: 2025-01-14 22:19:06.675533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29c0b0235a54'
down_revision: Union[str, None] = '810e9a86bc77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calls', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("TIMEZONE('utc', now())"),
               existing_nullable=False,
               schema='chatwave')
    op.alter_column('conversations_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("TIMEZONE('utc', now())"),
               existing_nullable=False,
               schema='chatwave')
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("TIMEZONE('utc', now())"),
               existing_nullable=False,
               schema='chatwave')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='chatwave')
    op.alter_column('conversations_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='chatwave')
    op.alter_column('calls', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='chatwave')
    # ### end Alembic commands ###
