"""Add nullable=true for field creator_id in table conversations

Revision ID: 4a06c5d8b599
Revises: 7784012e9e66
Create Date: 2025-01-24 15:40:38.710323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a06c5d8b599'
down_revision: Union[str, None] = '7784012e9e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='chatwave')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='chatwave')
    # ### end Alembic commands ###
