"""delete blocked_users table and relationships

Revision ID: 68a91c452065
Revises: 1700ae45e893
Create Date: 2025-01-19 20:29:25.457075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68a91c452065'
down_revision: Union[str, None] = '1700ae45e893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blocked_users', schema='chatwave')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_users',
    sa.Column('blocker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('blocked_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['chatwave.users.id'], name='blocked_users_blocked_id_fkey'),
    sa.ForeignKeyConstraint(['blocker_id'], ['chatwave.users.id'], name='blocked_users_blocker_id_fkey'),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id', name='blocked_users_pkey'),
    schema='chatwave'
    )
    # ### end Alembic commands ###
