"""set type field in table messages to nullable true

Revision ID: 745ce467b152
Revises: 8837bec2b062
Create Date: 2025-01-20 23:48:07.374753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '745ce467b152'
down_revision: Union[str, None] = '8837bec2b062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'type',
               existing_type=postgresql.ENUM('TEXT', 'IMAGE', 'VIDEO', 'AUDIO', 'FILE', 'VOICE', name='messagestypes'),
               nullable=True,
               schema='chatwave')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'type',
               existing_type=postgresql.ENUM('TEXT', 'IMAGE', 'VIDEO', 'AUDIO', 'FILE', 'VOICE', name='messagestypes'),
               nullable=False,
               schema='chatwave')
    # ### end Alembic commands ###
