"""Add on delete event for table conversations

Revision ID: 7784012e9e66
Revises: c6c1799d5ab3
Create Date: 2025-01-24 15:39:18.970770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7784012e9e66'
down_revision: Union[str, None] = 'c6c1799d5ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversations_creator_id_fkey', 'conversations', schema='chatwave', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['creator_id'], ['id'], source_schema='chatwave', referent_schema='chatwave', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', schema='chatwave', type_='foreignkey')
    op.create_foreign_key('conversations_creator_id_fkey', 'conversations', 'users', ['creator_id'], ['id'], source_schema='chatwave', referent_schema='chatwave')
    # ### end Alembic commands ###
