"""Add on add event for 'created_at' field in 'users' table

Revision ID: 810e9a86bc77
Revises: b1b8a424bac6
Create Date: 2025-01-14 20:46:13.411027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '810e9a86bc77'
down_revision: Union[str, None] = 'b1b8a424bac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("TIMEZONE('utc', now())"),
               existing_nullable=False,
               schema='chatwave')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='chatwave')
    # ### end Alembic commands ###
