"""Remove avatar_url field from Users

Revision ID: 937a7ab8dd9e
Revises: 29c0b0235a54
Create Date: 2025-01-16 10:26:13.333813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937a7ab8dd9e'
down_revision: Union[str, None] = '29c0b0235a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url', schema='chatwave')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True), schema='chatwave')
    # ### end Alembic commands ###
