"""change enums values

Revision ID: 98b3db371ae1
Revises: 26c1b8940f53
Create Date: 2025-02-03 22:03:50.055154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b3db371ae1'
down_revision: Union[str, None] = '26c1b8940f53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calls', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='chatwave')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calls', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='chatwave')
    # ### end Alembic commands ###
