"""first

Revision ID: b1b8a424bac6
Revises: 
Create Date: 2025-01-14 01:28:11.536110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1b8a424bac6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=128), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('last_online', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='chatwave'
    )
    op.create_index(op.f('ix_chatwave_users_nickname'), 'users', ['nickname'], unique=False, schema='chatwave')
    op.create_index('ix_users_username_passwordhash', 'users', ['username', 'password_hash'], unique=False, schema='chatwave')
    op.create_table('blocked_users',
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['chatwave.users.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['chatwave.users.id'], ),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id'),
    schema='chatwave'
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PRIVATE', 'GROUP', name='conversationtypes'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['chatwave.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='chatwave'
    )
    op.create_index(op.f('ix_chatwave_conversations_type'), 'conversations', ['type'], unique=False, schema='chatwave')
    op.create_index(op.f('ix_chatwave_conversations_updated_at'), 'conversations', ['updated_at'], unique=False, schema='chatwave')
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('caller_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMING', 'COMPLETED', 'MISSED', name='callsstatus'), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caller_id'], ['chatwave.users.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['chatwave.conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='chatwave'
    )
    op.create_index(op.f('ix_chatwave_calls_conversation_id'), 'calls', ['conversation_id'], unique=False, schema='chatwave')
    op.create_index(op.f('ix_chatwave_calls_started_at'), 'calls', ['started_at'], unique=False, schema='chatwave')
    op.create_table('conversations_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('CREATOR', 'ADMIN', 'MEMBER', name='conversationmemberroles'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chatwave.conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['chatwave.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'conversation_id'),
    schema='chatwave'
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'DELIVERED', 'READ', name='messagesstatus'), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'IMAGE', 'VIDEO', 'AUDIO', 'FILE', 'VOICE', name='messagestypes'), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('content_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['chatwave.conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['chatwave.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='chatwave'
    )
    op.create_index(op.f('ix_chatwave_messages_conversation_id'), 'messages', ['conversation_id'], unique=False, schema='chatwave')
    op.create_index(op.f('ix_chatwave_messages_created_at'), 'messages', ['created_at'], unique=False, schema='chatwave')
    op.create_index(op.f('ix_chatwave_messages_updated_at'), 'messages', ['updated_at'], unique=False, schema='chatwave')
    op.create_table('unread_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['chatwave.calls.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['chatwave.conversations.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['chatwave.messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['chatwave.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='chatwave'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unread_messages', schema='chatwave')
    op.drop_index(op.f('ix_chatwave_messages_updated_at'), table_name='messages', schema='chatwave')
    op.drop_index(op.f('ix_chatwave_messages_created_at'), table_name='messages', schema='chatwave')
    op.drop_index(op.f('ix_chatwave_messages_conversation_id'), table_name='messages', schema='chatwave')
    op.drop_table('messages', schema='chatwave')
    op.drop_table('conversations_members', schema='chatwave')
    op.drop_index(op.f('ix_chatwave_calls_started_at'), table_name='calls', schema='chatwave')
    op.drop_index(op.f('ix_chatwave_calls_conversation_id'), table_name='calls', schema='chatwave')
    op.drop_table('calls', schema='chatwave')
    op.drop_index(op.f('ix_chatwave_conversations_updated_at'), table_name='conversations', schema='chatwave')
    op.drop_index(op.f('ix_chatwave_conversations_type'), table_name='conversations', schema='chatwave')
    op.drop_table('conversations', schema='chatwave')
    op.drop_table('blocked_users', schema='chatwave')
    op.drop_index('ix_users_username_passwordhash', table_name='users', schema='chatwave')
    op.drop_index(op.f('ix_chatwave_users_nickname'), table_name='users', schema='chatwave')
    op.drop_table('users', schema='chatwave')
    # ### end Alembic commands ###
