"""Add cascade delete for tables

Revision ID: c6c1799d5ab3
Revises: 745ce467b152
Create Date: 2025-01-23 20:10:51.794040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6c1799d5ab3'
down_revision: Union[str, None] = '745ce467b152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversations_members_conversation_id_fkey', 'conversations_members', schema='chatwave', type_='foreignkey')
    op.drop_constraint('conversations_members_user_id_fkey', 'conversations_members', schema='chatwave', type_='foreignkey')
    op.create_foreign_key(None, 'conversations_members', 'users', ['user_id'], ['id'], source_schema='chatwave', referent_schema='chatwave', ondelete='CASCADE')
    op.create_foreign_key(None, 'conversations_members', 'conversations', ['conversation_id'], ['id'], source_schema='chatwave', referent_schema='chatwave', ondelete='CASCADE')
    op.drop_constraint('messages_sender_id_fkey', 'messages', schema='chatwave', type_='foreignkey')
    op.drop_constraint('messages_conversation_id_fkey', 'messages', schema='chatwave', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], source_schema='chatwave', referent_schema='chatwave', ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], source_schema='chatwave', referent_schema='chatwave', ondelete='CASCADE')
    op.drop_constraint('unread_messages_message_id_fkey', 'unread_messages', schema='chatwave', type_='foreignkey')
    op.drop_constraint('unread_messages_conversation_id_fkey', 'unread_messages', schema='chatwave', type_='foreignkey')
    op.drop_constraint('unread_messages_call_id_fkey', 'unread_messages', schema='chatwave', type_='foreignkey')
    op.drop_constraint('unread_messages_user_id_fkey', 'unread_messages', schema='chatwave', type_='foreignkey')
    op.create_foreign_key(None, 'unread_messages', 'calls', ['call_id'], ['id'], source_schema='chatwave', referent_schema='chatwave', ondelete='CASCADE')
    op.create_foreign_key(None, 'unread_messages', 'messages', ['message_id'], ['id'], source_schema='chatwave', referent_schema='chatwave', ondelete='CASCADE')
    op.create_foreign_key(None, 'unread_messages', 'users', ['user_id'], ['id'], source_schema='chatwave', referent_schema='chatwave', ondelete='CASCADE')
    op.create_foreign_key(None, 'unread_messages', 'conversations', ['conversation_id'], ['id'], source_schema='chatwave', referent_schema='chatwave', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unread_messages', schema='chatwave', type_='foreignkey')
    op.drop_constraint(None, 'unread_messages', schema='chatwave', type_='foreignkey')
    op.drop_constraint(None, 'unread_messages', schema='chatwave', type_='foreignkey')
    op.drop_constraint(None, 'unread_messages', schema='chatwave', type_='foreignkey')
    op.create_foreign_key('unread_messages_user_id_fkey', 'unread_messages', 'users', ['user_id'], ['id'], source_schema='chatwave', referent_schema='chatwave')
    op.create_foreign_key('unread_messages_call_id_fkey', 'unread_messages', 'calls', ['call_id'], ['id'], source_schema='chatwave', referent_schema='chatwave')
    op.create_foreign_key('unread_messages_conversation_id_fkey', 'unread_messages', 'conversations', ['conversation_id'], ['id'], source_schema='chatwave', referent_schema='chatwave')
    op.create_foreign_key('unread_messages_message_id_fkey', 'unread_messages', 'messages', ['message_id'], ['id'], source_schema='chatwave', referent_schema='chatwave')
    op.drop_constraint(None, 'messages', schema='chatwave', type_='foreignkey')
    op.drop_constraint(None, 'messages', schema='chatwave', type_='foreignkey')
    op.create_foreign_key('messages_conversation_id_fkey', 'messages', 'conversations', ['conversation_id'], ['id'], source_schema='chatwave', referent_schema='chatwave')
    op.create_foreign_key('messages_sender_id_fkey', 'messages', 'users', ['sender_id'], ['id'], source_schema='chatwave', referent_schema='chatwave')
    op.drop_constraint(None, 'conversations_members', schema='chatwave', type_='foreignkey')
    op.drop_constraint(None, 'conversations_members', schema='chatwave', type_='foreignkey')
    op.create_foreign_key('conversations_members_user_id_fkey', 'conversations_members', 'users', ['user_id'], ['id'], source_schema='chatwave', referent_schema='chatwave')
    op.create_foreign_key('conversations_members_conversation_id_fkey', 'conversations_members', 'conversations', ['conversation_id'], ['id'], source_schema='chatwave', referent_schema='chatwave')
    # ### end Alembic commands ###
