"""add content_name and content_type fields to messages table

Revision ID: da4d4438e254
Revises: 68a91c452065
Create Date: 2025-01-20 19:43:34.394407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4d4438e254'
down_revision: Union[str, None] = '68a91c452065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('file_content_name', sa.String(), nullable=True), schema='chatwave')
    op.add_column('messages', sa.Column('file_content_type', sa.String(), nullable=True), schema='chatwave')
    op.drop_column('messages', 'content_url', schema='chatwave')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('content_url', sa.VARCHAR(), autoincrement=False, nullable=True), schema='chatwave')
    op.drop_column('messages', 'file_content_type', schema='chatwave')
    op.drop_column('messages', 'file_content_name', schema='chatwave')
    # ### end Alembic commands ###
