"""add avatar_name and avatar_type fields to Users table

Revision ID: e7f9f9d0ac0f
Revises: da78da733c86
Create Date: 2025-01-18 17:53:00.835794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f9f9d0ac0f'
down_revision: Union[str, None] = 'da78da733c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_name', sa.String(), nullable=True), schema='chatwave')
    op.add_column('users', sa.Column('avatar_type', sa.String(), nullable=True), schema='chatwave')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_type', schema='chatwave')
    op.drop_column('users', 'avatar_name', schema='chatwave')
    # ### end Alembic commands ###
